name: Zadanie1

on:
  push:
    branches: [main]

jobs:
  build-push-images:
    name: Budowa i publikacja obrazu na repozytorium DockerHub
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      # Użycie QEMU
      - name: QEMU set-up
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      
      # Użycie Buildx
      - name: Buildx set-up
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      # Logowanie do GitHub CR
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}


      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
          push: true
          tags: ghcr.io/jaksaw68/zadanie1:dodatek1
          cache-from: type=registry,ref=ghcr.io/jaksaw68/zadanie1:dodatek1
          cache-to: type=inline
